name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      version:
        description: '版本号'
        required: true
permissions:
  contents: write
  discussions: write
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -r win-x64 -p:PublishReadyToRun=true -p:PublishSingleFile=true

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Get release content
      id: create_release
      run: |
          cd ${{ github.workspace }}
          pwd && ls
          content=$(tac ./CHANGELOG.md | grep -m1 "##" -B 1000 | tac)
          echo "Release content: $content"
          echo "release_content<<EOF" >> $GITHUB_OUTPUT
          echo "$content" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
    - name: file-list
      run: find -name '*.exe'
      
    - name: Upload release asset
      id: upload-release-asset 
      uses: softprops/action-gh-release@v1
      with:
          files: |
           bin/Release/net7.0/win-x64/publish/*.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          name: DataProcess-V${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          body: ${{ steps.release_content.outputs.release_content }}
          discussion_category_name: Announcements
          generate_release_notes: true
          fail_on_unmatched_files: true
